import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "./components/nav";
import { getUser } from "./api/auth/[...nextauth]/route";;
import Login from "./components/login";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser()

return(
  <html lang="en">
  <body >
  <> 
    {user === undefined ? (
      <Login/> 
       ) :(
         <>
         <Nav/>
     {children}
         </>
       )
     }
</>
  </body>
</html>

)
     
    }
