import type { Metadata } from "next";
import "./globals.css";
import { getUser } from "./api/auth/[...nextauth]/route";;
import ConvexClientProvider from "@/ConvexClientProvider";
import ProtectRoute from "./routeProtect";
import { ThemeProvider } from "./theme-provider"
import { useTheme } from "next-themes";
export const metadata: Metadata = {
  title: "DreamShop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser()

return(
  <html lang="en">
    <body>
      <ConvexClientProvider>
<ProtectRoute user={user}>
  {children}
</ProtectRoute>
      </ConvexClientProvider>

    </body>
</html>

)
     
    }
/*

*/